apiVersion: v1
kind: Deployment
metadata:
  name: dnsutils-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dnsutil
    spec:
      containers:
      - name: dnsutils
        image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always